SECRET_KEY = 'YOUR SESSION SECRET KEY'

OAUTH_CLIENT_ID = 'YOUR OAUTH CLIENT ID'

OAUTH_CLIENT_SECRET = "YOUR OUATH CLIENT SECRET"
OAUTH_AUTHORIZATION_BASE_URL = "YOUR OAUTH AUTHORIZATION BASE URL"
OAUTH_REDIRECT_URI = "YOUR OAUTH REDIRECT URL"
OAUTH_TOKEN_URL = "YOUR OAUTH TOKEN URL"
OAUTH_SCOPE = "profile"

LOGIN_JWT_SECRET = "YOUR LOGIN JWT SECRET"

SPOTIFY_USERNAME = 'YOUR SPOTIFY USERNAME'
SPOTIFY_PASSWORD = 'YOUR SPOTIFY PASSWORD'
SPOTIFY_CLIENT_ID = 'YOUR SPOTIFY CLIENT ID'
SPOTIFY_CLIENT_SECRET = 'YOUR SPOTIFY_CLIENT_SECRET'