SECRET_KEY = "YOUR SESSION SECRET KEY"

OAUTH_GOOGLE_CLIENT_ID = "YOUR OAUTH CLIENT ID"
OAUTH_GOOGLE_CLIENT_SECRET = "YOUR OAUTH CLIENT SECRET"
OAUTH_GOOGLE_REDIRECT_URI = "YOUR OAUTH REDIRECT URL"

OAUTH_SPOTIFY_CLIENT_ID = "YOUR OAUTH CLIENT ID"
OAUTH_SPOTIFY_CLIENT_SECRET = "YOUR OAUTH CLIENT SECRET"
OAUTH_SPOTIFY_REDIRECT_URI = "YOUR OAUTH REDIRECT URL"
OAUTH_SPOTIFY_TEST_TOKEN = "YOUR OAUTH SPOTIFY TEST TOKEN"

LOGIN_JWT_SECRET = "YOUR LOGIN JWT SECRET"

SPOTIFY_CACHE_LOCATION = "./.cache"
SPOTIFY_CLIENT_ID = "YOUR SPOTIFY CLIENT ID"
SPOTIFY_CLIENT_SECRET = "YOUR SPOTIFY_CLIENT_SECRET"
SPOTIFY_HLS_LOCATION = "./hls/segment%05d.ts"
SPOTIFY_HLS_PLAYLIST_LOCATION = "./hls/playlist.m3u8"
SPOTIFY_HLS_PLAYLIST_ROOT = "YOUR HLS PLAYLIST ROOT"
SPOTIFY_HLS_PLAYLIST_LENGTH = 20
SPOTIFY_HLS_TARGET_DURATION = 6
SPOTIFY_HLS_MAX_FILES = 30
# support SimpleNextTrackQueue, RoundRobinNextTrackQueue
SPOTIFY_QUEUE_TYPE = "RoundRobinNextTrackQueue"
# support GYRESPOT, PYSPOTIFY
SPOTIFY_BACKEND_TYPE = "GYRESPOT"

LOGIN_VALID_CALLBACK_URLS = []

LYRICS_SEARCH_LYRICS_PATH = "YOUR LYRICS PATH"
LYRICS_SEARCH_INDEX_PATH = "YOUR LYRICS INDEX PATH"
