SECRET_KEY = 'YOUR SESSION SECRET KEY'

OAUTH_CLIENT_ID = 'YOUR OAUTH CLIENT ID'

OAUTH_CLIENT_SECRET = "YOUR OUATH CLIENT SECRET"
OAUTH_AUTHORIZATION_BASE_URL = "YOUR OAUTH AUTHORIZATION BASE URL"
OAUTH_REDIRECT_URI = "YOUR OAUTH REDIRECT URL"
OAUTH_TOKEN_URL = "YOUR OAUTH TOKEN URL"
OAUTH_SCOPE = "profile"

LOGIN_JWT_SECRET = "YOUR LOGIN JWT SECRET"

SPOTIFY_USERNAME = 'YOUR SPOTIFY USERNAME'
SPOTIFY_PASSWORD = 'YOUR SPOTIFY PASSWORD'
SPOTIFY_CLIENT_ID = 'YOUR SPOTIFY CLIENT ID'
SPOTIFY_CLIENT_SECRET = 'YOUR SPOTIFY_CLIENT_SECRET'
SPOTIFY_HLS_PLAYLIST_LOCATION = "YOUR HLS PLAYLIST LOCATION"
SPOTIFY_HLS_PLAYLIST_ROOT = "YOUR HLS PLAYLIST ROOT"
SPOTIFY_HLS_PLAYLIST_LENGTH = 20
SPOTIFY_HLS_TARGET_DURATION = 6
SPOTIFY_HLS_MAX_FILES = 30

LOGIN_VALID_CALLBACK_URLS = []